apiVersion: apps/v1
kind: Deployment
metadata:
  name: medisynth-api
  namespace: medisynth-io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medisynth-api
  template:
    metadata:
      labels:
        app: medisynth-api
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: medisynth-api
          image: ghcr.io/medisynth-io/medisynth-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: http
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /heartbeat
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /heartbeat
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: sqlite-data
              mountPath: /data
            - name: config
              mountPath: /app
          env:
            - name: CONFIG_PATH
              value: "/app/app.prod.yml"
            - name: DB_PATH
              value: /data/medisynth.db
            - name: MEDISYNTH_SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: medisynth-secrets
                  key: session-secret
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
      initContainers:
        - name: init-db
          image: keinos/sqlite3
          command: ["sh", "-c", "mkdir -p /data && touch /data/medisynth.db && sqlite3 /data/medisynth.db 'PRAGMA journal_mode=WAL;' && chmod 777 /data/medisynth.db && chmod 777 /data"]
          volumeMounts:
            - name: sqlite-data
              mountPath: /data
          securityContext:
            runAsUser: 0
      volumes:
        - name: sqlite-data
          persistentVolumeClaim:
            claimName: medisynth-sqlite-pvc
        - name: config
          configMap:
            name: medisynth-config 