apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - sqlite-pvc.yaml

commonLabels:
  app.kubernetes.io/part-of: medisynth-api

namespace: medisynth-io 