apiVersion: v1
kind: Service
metadata:
  name: medisynth-portal-service
  namespace: medisynth-io
spec:
  selector:
    app: medisynth-io
    tier: backend
    component: portal
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: http 