apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medisynth-sqlite-pvc
  namespace: medisynth-io
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage 