version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: .devops/docker/api/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - sqlite_data:/app/data
    environment:
      - CONFIG_DIR=/app/config
    configs:
      - source: app_config
        target: /app/config/app.yml

volumes:
  sqlite_data:
    driver: local

configs:
  app_config:
    file: ./app.yml
