# Use Go 1.23 for the build stage
FROM golang:1.23 AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=1 go build -o /app/medisynth-api ./cmd/api/main.go

# Use a debian-based image for the final stage
FROM debian:stable-slim
WORKDIR /app
COPY --from=builder /app/medisynth-api /app/medisynth-api
CMD ["./medisynth-api"] 