apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medisynth-io

resources:
  - ../../base
  - namespace.yaml
  - ingress-patch.yaml

patchesStrategicMerge:
  - ingress-patch.yaml 